DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'modeles_documents_titre_unique'
  ) THEN
    ALTER TABLE public.modeles_documents
    ADD CONSTRAINT modeles_documents_titre_unique UNIQUE (titre);
  END IF;
END $$;

INSERT INTO public.modeles_documents (titre, categorie, actif, contenu_template)
VALUES
('Mandat de recherche', 'mandat_recherche', true, $${"sections": [{"id": "header", "type": "header", "titre": "MANDAT DE RECHERCHE IMMOBILIÈRE", "contenu": "Établi entre HUNTERS Immobilier et le client mandant"}, {"id": "parties", "type": "text", "titre": "PARTIES", "contenu": "Le Mandant : {{nom_client}}\nEmail : {{email_client}}\nTéléphone : {{telephone_client}}\n\nLe Mandataire : {{cabinet_nom}}\nReprésenté par : {{conseiller}}\nN° RSAC : {{conseiller_rsac}} — Greffe de {{conseiller_greffe}}\nCarte T : {{carte_t}}\nSIRET : {{cabinet_siret}}"}, {"id": "objet", "type": "text", "titre": "OBJET DU MANDAT", "contenu": "Le Mandant confie à HUNTERS Immobilier la mission de recherche d'un bien immobilier selon les critères définis, pour un budget de {{budget}}, dans la ville de {{ville}}."}, {"id": "honoraires", "type": "text", "titre": "HONORAIRES", "contenu": "Honoraires convenus : {{honoraires}} HT (TVA 20% en sus).\nConseil stratégique patrimonial préalable : {{tarif_conseil}} HT — facturé au tarif plein, aucune remise autorisée."}, {"id": "signatures", "type": "signatures", "titre": "SIGNATURES", "contenu": "Fait à Tours, le {{date}}"}]}$$::jsonb),
('Convention d''honoraires — Conseil patrimonial', 'convention_honoraires', true, $${"sections": [{"id": "header", "type": "header", "titre": "CONVENTION D'HONORAIRES", "contenu": "Conseil en stratégie patrimoniale et investissement immobilier"}, {"id": "parties", "type": "text", "titre": "PARTIES", "contenu": "Le Client : {{nom_client}} — {{email_client}} — {{telephone_client}}\n\nLe Cabinet : {{cabinet_nom}} — {{cabinet_adresse}}\nReprésenté par : {{conseiller}} — Carte T : {{carte_t}}"}, {"id": "mission", "type": "text", "titre": "MISSION", "contenu": "HUNTERS Immobilier s'engage à réaliser un rapport de conseil en stratégie patrimoniale et investissement immobilier couvrant : profil et capacité de financement, stratégie d'investissement, montages juridiques et fiscaux recommandés, scénarios comparatifs, recommandations personnalisées.\n\nNiveau de complexité : {{niveau_client}}\nScore de qualification : {{score_qualification}}/10"}, {"id": "honoraires", "type": "text", "titre": "HONORAIRES", "contenu": "Honoraires forfaitaires : {{tarif_conseil}} HT (TVA 20% en sus).\nAcompte de 50% exigible à la signature de la présente convention.\nSolde de 50% exigible à la remise du rapport (délai maximum 15 jours).\nCes honoraires sont fermes et non remisables."}, {"id": "signatures", "type": "signatures", "titre": "SIGNATURES", "contenu": "Fait à Tours, le {{date}}\nLu et approuvé — Bon pour accord"}]}$$::jsonb),
('Lettre de mission AMO', 'lettre_mission_amo', true, $${"sections": [{"id": "header", "type": "header", "titre": "LETTRE DE MISSION", "contenu": "Assistance à Maîtrise d'Ouvrage — Suivi de travaux"}, {"id": "parties", "type": "text", "titre": "PARTIES", "contenu": "Le Maître d'Ouvrage : {{nom_client}} — {{email_client}}\n\nL'Assistant à Maîtrise d'Ouvrage : {{cabinet_nom}}\nReprésenté par : {{conseiller}} — Carte T : {{carte_t}}"}, {"id": "mission", "type": "text", "titre": "MISSION", "contenu": "HUNTERS Immobilier est mandaté pour assurer le suivi et la coordination des travaux de rénovation du bien situé à {{ville}}.\n\nMission : coordination des intervenants, suivi planning, contrôle qualité, réception des travaux, interface technique avec le Maître d'Ouvrage."}, {"id": "honoraires", "type": "financier", "titre": "HONORAIRES AMO", "champs": [{"key": "montant_travaux", "type": "number", "label": "Montant total des travaux HT (€)", "defaut": 0, "auto_from": "budget"}, {"key": "forfait_amo", "type": "number", "label": "Forfait fixe AMO (€)", "defaut": 2000}, {"key": "taux_amo", "type": "number", "label": "Taux variable AMO (%)", "defaut": 10}, {"key": "honoraires_variables", "type": "calc", "label": "Honoraires variables (€)", "formule": "montant_travaux * taux_amo / 100"}, {"key": "total_amo_ht", "type": "calc", "label": "Total honoraires AMO HT (€)", "formule": "forfait_amo + honoraires_variables"}]}, {"id": "signatures", "type": "signatures", "titre": "SIGNATURES", "contenu": "Fait à Tours, le {{date}}\nLu et approuvé — Bon pour accord"}]}$$::jsonb),
('Lettre de mission Décoration & ameublement', 'lettre_mission_deco', true, $${"sections": [{"id": "header", "type": "header", "titre": "LETTRE DE MISSION", "contenu": "Décoration & ameublement — Mise en valeur locative"}, {"id": "parties", "type": "text", "titre": "PARTIES", "contenu": "Le Client : {{nom_client}} — {{email_client}}\n\nLe Prestataire : {{cabinet_nom}}\nReprésenté par : {{conseiller}} — Carte T : {{carte_t}}"}, {"id": "mission", "type": "text", "titre": "MISSION", "contenu": "HUNTERS Immobilier est mandaté pour assurer la conception, le sourcing et la mise en place de la décoration et de l'ameublement du bien situé à {{ville}}, dans une optique de mise en valeur locative premium."}, {"id": "honoraires", "type": "financier", "titre": "HONORAIRES DÉCORATION", "champs": [{"key": "budget_deco", "type": "number", "label": "Budget décoration & ameublement HT (€)", "defaut": 0}, {"key": "forfait_deco", "type": "number", "label": "Forfait fixe décoration (€)", "defaut": 2500}, {"key": "taux_deco", "type": "number", "label": "Taux variable décoration (%)", "defaut": 15}, {"key": "honoraires_variables", "type": "calc", "label": "Honoraires variables (€)", "formule": "budget_deco * taux_deco / 100"}, {"key": "total_deco_ht", "type": "calc", "label": "Total honoraires décoration HT (€)", "formule": "forfait_deco + honoraires_variables"}]}, {"id": "signatures", "type": "signatures", "titre": "SIGNATURES", "contenu": "Fait à Tours, le {{date}}\nLu et approuvé — Bon pour accord"}]}$$::jsonb),
('Contrat Pack clé en main', 'contrat_pack', true, $${"sections": [{"id": "header", "type": "header", "titre": "CONTRAT PACK CLÉ EN MAIN", "contenu": "Conseil · Chasse · AMO · Décoration & ameublement"}, {"id": "parties", "type": "text", "titre": "PARTIES", "contenu": "Le Client : {{nom_client}} — {{email_client}} — {{telephone_client}}\n\nLe Cabinet : {{cabinet_nom}} — {{cabinet_adresse}}\nReprésenté par : {{conseiller}} — N° RSAC : {{conseiller_rsac}}\nCarte T : {{carte_t}} — SIRET : {{cabinet_siret}}"}, {"id": "services", "type": "services_conditionnels", "titre": "SERVICES SOUSCRITS", "contenu": "Dans le cadre du Pack clé en main, le Client souscrit aux services suivants :\n{{services_liste}}\n\nConseil patrimonial préalable : {{tarif_conseil}} HT — tarif plein, aucune remise.\nRemise Pack 10% appliquée sur chasse, AMO et décoration."}, {"id": "honoraires", "type": "financier", "titre": "RÉCAPITULATIF HONORAIRES", "champs": [{"key": "honoraires_conseil", "type": "number", "label": "Conseil patrimonial HT (€) — tarif plein", "defaut": 1500}, {"key": "honoraires_chasse", "type": "number", "label": "Chasse immobilière HT avant remise (€)", "defaut": 0}, {"key": "honoraires_amo", "type": "number", "label": "AMO HT avant remise (€)", "defaut": 0}, {"key": "honoraires_deco", "type": "number", "label": "Décoration HT avant remise (€)", "defaut": 0}, {"key": "base_remisable", "type": "calc", "label": "Base remisable (chasse + AMO + déco)", "formule": "honoraires_chasse + honoraires_amo + honoraires_deco"}, {"key": "remise_pack", "type": "calc", "label": "Remise Pack 10% (€)", "formule": "base_remisable * 0.10"}, {"key": "total_ht", "type": "calc", "label": "TOTAL HONORAIRES HT (€)", "formule": "honoraires_conseil + base_remisable - remise_pack"}]}, {"id": "rappel_prix", "type": "text", "titre": "RAPPEL POLITIQUE TARIFAIRE", "contenu": "Le service de conseil stratégique patrimonial est facturé au tarif plein en toutes circonstances. La remise Pack de 10% s'applique exclusivement aux services de chasse, AMO et décoration. Aucune remise supplémentaire ne peut être accordée sans autorisation écrite du Directeur."}, {"id": "signatures", "type": "signatures", "titre": "SIGNATURES", "contenu": "Fait à Tours, le {{date}}\nLu et approuvé — Bon pour accord"}]}$$::jsonb),
('Compte-rendu de visite de bien', 'compte_rendu', true, $${"sections": [{"id": "header", "type": "header", "titre": "COMPTE-RENDU DE VISITE", "contenu": "Rapport de visite — Dossier n° {{numero_dossier}}"}, {"id": "infos", "type": "text", "titre": "INFORMATIONS GÉNÉRALES", "contenu": "Client : {{nom_client}}\nConseiller : {{conseiller}}\nDate de visite : {{date}}\nVille : {{ville}}\nBudget cible : {{budget}}"}, {"id": "bien", "type": "text", "titre": "BIEN VISITÉ", "contenu": "Adresse du bien :\n\nType de bien :\n\nSurface :\n\nPrix demandé :\n\nCharges de copropriété :\n\nDPE :"}, {"id": "analyse", "type": "financier", "titre": "ANALYSE FINANCIÈRE", "champs": [{"key": "prix_bien", "type": "number", "label": "Prix d'acquisition HT (€)", "defaut": 0, "auto_from": "budget"}, {"key": "loyer_mensuel", "type": "number", "label": "Loyer mensuel estimé (€)", "defaut": 0}, {"key": "loyer_annuel", "type": "calc", "label": "Loyer annuel brut (€)", "formule": "loyer_mensuel * 12"}, {"key": "rendement_brut", "type": "calc", "label": "Rendement brut (%)", "formule": "prix_bien > 0 ? (loyer_annuel / prix_bien * 100) : 0"}, {"key": "charges_annuelles", "type": "number", "label": "Charges annuelles estimées (€)", "defaut": 0}, {"key": "loyer_net", "type": "calc", "label": "Loyer net annuel (€)", "formule": "loyer_annuel - charges_annuelles"}, {"key": "rendement_net", "type": "calc", "label": "Rendement net (%)", "formule": "prix_bien > 0 ? (loyer_net / prix_bien * 100) : 0"}]}, {"id": "avis", "type": "text", "titre": "AVIS ET RECOMMANDATIONS", "contenu": "Points positifs :\n\nPoints de vigilance :\n\nRecommandation HUNTERS :"}, {"id": "signatures", "type": "signatures", "titre": "SIGNATURES", "contenu": "Fait à Tours, le {{date}}"}]}$$::jsonb)
ON CONFLICT ON CONSTRAINT modeles_documents_titre_unique
DO UPDATE SET
  categorie = EXCLUDED.categorie,
  actif = EXCLUDED.actif,
  contenu_template = EXCLUDED.contenu_template,
  updated_at = now();