ALTER TABLE public.dossiers
  ADD COLUMN IF NOT EXISTS date_naissance date,
  ADD COLUMN IF NOT EXISTS nationalite text,
  ADD COLUMN IF NOT EXISTS situation_familiale text,
  ADD COLUMN IF NOT EXISTS regime_matrimonial text,
  ADD COLUMN IF NOT EXISTS nombre_enfants integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ages_enfants text,
  ADD COLUMN IF NOT EXISTS statut_professionnel text,
  ADD COLUMN IF NOT EXISTS profession text,
  ADD COLUMN IF NOT EXISTS secteur_activite text,
  ADD COLUMN IF NOT EXISTS anciennete_emploi text,
  ADD COLUMN IF NOT EXISTS residence_principale text,
  ADD COLUMN IF NOT EXISTS revenus_nets_mensuels numeric,
  ADD COLUMN IF NOT EXISTS revenus_conjoint numeric,
  ADD COLUMN IF NOT EXISTS revenus_locatifs_existants numeric,
  ADD COLUMN IF NOT EXISTS autres_revenus numeric,
  ADD COLUMN IF NOT EXISTS charges_mensuelles_fixes numeric,
  ADD COLUMN IF NOT EXISTS capacite_epargne_mensuelle numeric,
  ADD COLUMN IF NOT EXISTS epargne_disponible numeric,
  ADD COLUMN IF NOT EXISTS apport_disponible numeric,
  ADD COLUMN IF NOT EXISTS tmi integer,
  ADD COLUMN IF NOT EXISTS revenus_fiscaux_reference numeric,
  ADD COLUMN IF NOT EXISTS impot_revenu_paye numeric,
  ADD COLUMN IF NOT EXISTS assujetti_ifi boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS deficits_fonciers_existants numeric,
  ADD COLUMN IF NOT EXISTS dispositifs_fiscaux_en_cours text,
  ADD COLUMN IF NOT EXISTS objectif_fiscal text,
  ADD COLUMN IF NOT EXISTS residence_principale_valeur numeric,
  ADD COLUMN IF NOT EXISTS residence_principale_crd numeric,
  ADD COLUMN IF NOT EXISTS biens_locatifs_existants jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS epargne_financiere jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS autres_actifs text,
  ADD COLUMN IF NOT EXISTS passif_total numeric,
  ADD COLUMN IF NOT EXISTS taux_endettement_actuel numeric,
  ADD COLUMN IF NOT EXISTS objectif_principal text,
  ADD COLUMN IF NOT EXISTS horizon_investissement text,
  ADD COLUMN IF NOT EXISTS appetence_risque text,
  ADD COLUMN IF NOT EXISTS contraintes_geographiques text,
  ADD COLUMN IF NOT EXISTS type_bien_souhaite text,
  ADD COLUMN IF NOT EXISTS type_location_souhaite text,
  ADD COLUMN IF NOT EXISTS aversion_gestion text,
  ADD COLUMN IF NOT EXISTS banque_principale text,
  ADD COLUMN IF NOT EXISTS credits_en_cours jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS capacite_emprunt_estimee numeric,
  ADD COLUMN IF NOT EXISTS duree_credit_souhaitee integer,
  ADD COLUMN IF NOT EXISTS preference_taux text,
  ADD COLUMN IF NOT EXISTS deja_rencontre_banque boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS delai_concretisation text,
  ADD COLUMN IF NOT EXISTS contraintes_particulieres text,
  ADD COLUMN IF NOT EXISTS source_recommandation text;