ALTER TABLE public.dossiers
  ADD COLUMN IF NOT EXISTS grille_controle JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS grille_validee_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS grille_validee_par TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS grille_statut TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS grille_modifications JSONB DEFAULT NULL;